name: Telegram PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        run: |
          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="New PR: ${{ github.event.pull_request.title }}%0AURL: ${{ github.event.pull_request.html_url }}" \
            -d parse_mode="Markdown"    
